### ISSUE TITLE
Misleading display

### ISSUE THREAD

**Issue by zhoukai07** [CS2103AUG2017-T17-B3/main#59]
If I use command line to find/add/find a contact name, the main window displays the correct contact accordingly. However, side panel(browser) does not respond. 
Side panel only reacts when user click on the contact itself. 
this might be confusing for a user after several commands are keyed in.
For example, I clicked on Bernice, added a new contact then find a contact, the display is shown below: 

![image](https://user-images.githubusercontent.com/19451453/32363621-373bd292-c0ab-11e7-8710-ebc518902641.png)

**Comment by eldonng** [comment]
Hi. Just to clarify, the side panel you are referring to is the web browser panel right?
