### ISSUE TITLE
Adding multiple people with the same name but different fields

### ISSUE THREAD

**Issue by hansiang93** [CS2103AUG2017-T17-B3/main#60]
![image](https://user-images.githubusercontent.com/12292130/32363717-98151a2e-c0ab-11e7-8c52-2158d99eb518.png)

adding "alex yeoh" with and address, and another "alex yeoh" with nothing will create 2 instances.

Equals should only look at name.

**Comment by eldonng** [comment]
Hi. Thanks for highlighting the issue. However, there are possibilities that 2 or more people have the same name. So i dont really think that we should only be comparing the name. 
Perhaps we will compare only name and phone. Thanks!
